In [ ]:
#statistics

In [ ]:
#importing np

In [1]:
import numpy as np

In [2]:
#creating a data set

In [3]:
list1 = ["Bien", "Kinoti", "Bensoul", "Nikita", "Nyashinski"]
list2 = [120000, 2000000, 150000, 250000, 400000]
list3 = [245000, 3000000, 250000, 1000000, 2000000]

kenyan_artist = np.array(list1) 
spotify_streams = np.array(list2)
apple_streams = np.array(list3)
type(kenyan_artist)


numpy.ndarray

In [ ]:
#calculating total streams

In [5]:
total_streams = np.add(spotify_streams, apple_streams)
print(total_streams)
                    

[ 365000 5000000  400000 1250000 2400000]


In [6]:
total_streams = np.subtract(spotify_streams, apple_streams)
total_streams

array([ -125000, -1000000,  -100000,  -750000, -1600000])

In [13]:
spotify_streams * 2

array([ 240000, 4000000,  300000,  500000,  800000])